---
title: "Testing Color Palettes"
author: "Dave Bosworth"
date: "12/24/2019"
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import and Prepare Data

Load R packages necessary for this analysis:
```{r load packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(scales)
library(colorspace)
library(openwaterhg)
```

Import and Clean Load Data:
```{r import and clean load data, message = FALSE, warning = FALSE}
# Import Load Data
source("YB_Mass_Balance/Loads/Import_Inlet_Load_Data.R")

# Clean loads_orig
loads_clean <- loads_inlet %>% 
  # only include THg and MeHg
  filter(str_detect(Analyte, "^THg|^MeHg")) %>% 
  select(
    SamplingEvent,
    StationName,
    Analyte,
    Load,
    LoadUnits
  ) %>% 
  # apply factor order to SamplingEvent and StationName variables
  conv_fact_inlet_names() %>% 
  conv_fact_samplingevent()
```


# Create Base Plots

Stacked Bar Plots:
```{r base plot stacked}
plot_stacked <- loads_clean %>% 
  ggplot(
    aes(
      x = SamplingEvent,
      y = Load,
      fill = StationName
    )
  ) +
  geom_col() +
  facet_wrap(
    vars(Analyte, LoadUnits),
    ncol = 3, 
    scales = "free_y",
  ) +
  labs(
    title = NULL,
    x = "Sampling Event",
    y = "Loads"
  ) +
  theme_owhg(x_axis_v = TRUE)
```

Filled Bar Plots:
```{r base plot filled}
plot_filled <- loads_clean %>% 
  ggplot(
    aes(
      x = SamplingEvent,
      y = Load,
      fill = StationName
    )
  ) +
  geom_col(position = "fill") +
  facet_wrap(
    vars(Analyte, LoadUnits),
    ncol = 3, 
    scales = "free_y",
  ) +
  labs(
    title = NULL,
    x = "Sampling Event",
    y = "Percentage of Total Inlet Load"
  ) +
  theme_owhg(x_axis_v = TRUE) +
  scale_y_continuous(labels = percent_format())
```


# Example Plots

## Viridis

Stacked Bar Plot:
```{r plot stacked viridis, fig.width = 10, fig.height = 6}
plot_stacked + scale_fill_discrete_sequential(palette = "Viridis", nmax = 5)
```

Filled Bar Plot:
```{r plot filled viridis, fig.width = 10, fig.height = 6}
plot_filled + scale_fill_discrete_sequential(palette = "Viridis", nmax = 5)
```


## Yellow-Green-Blue (YlGnBu)

Stacked Bar Plot:
```{r plot stacked YlGnBu, fig.width = 10, fig.height = 6}
plot_stacked + scale_fill_discrete_sequential(palette = "YlGnBu", nmax = 6, order = 2:6)
```

Filled Bar Plot:
```{r plot filled YlGnBu, fig.width = 10, fig.height = 6}
plot_filled + scale_fill_discrete_sequential(palette = "YlGnBu", nmax = 6, order = 2:6)
```


## Yellow-Orange-Red (YlOrRd)

Stacked Bar Plot:
```{r plot stacked YlOrRd, fig.width = 10, fig.height = 6}
plot_stacked + scale_fill_discrete_sequential(palette = "YlOrRd", nmax = 6, order = 2:6)
```

Filled Bar Plot:
```{r plot filled YlOrRd, fig.width = 10, fig.height = 6}
plot_filled + scale_fill_discrete_sequential(palette = "YlOrRd", nmax = 6, order = 2:6)
```

